version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:latest
    ports:
      - "3001:3001"
    volumes:
      - ./devnet:/data
    environment:
      - CARDANO_BLOCK_PRODUCER=true
      - CARDANO_SOCKET_PATH=/data/ipc/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/ipc/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/data/cardano-node.json"
      , "--topology", "/data/topology.json"
      , "--database-path", "/data/db"
      , "--shelley-kes-key", "/data/kes.skey"
      , "--shelley-vrf-key", "/data/vrf.skey"
      , "--shelley-operational-certificate", "/data/opcert.cert"
      , "--host-addr", "127.0.0.1"
      , "--port", "3001"
      , "--byron-delegation-certificate", "/data/byron-delegation.cert"
      , "--byron-signing-key", "/data/byron-delegate.key"
      ]
