dbConfig:
    dbConfigFile: pab-core.db
    dbConfigPoolSize: 20

pabWebserverConfig:
  baseUrl: http://localhost:9080
  staticDir: plutus-pab-client/dist
  permissiveCorsPolicy: False
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 5
  enableMarconi: False

walletServerConfig:
  tag: LocalWalletConfig
  walletSettings:
    baseUrl: http://localhost:8090

nodeServerConfig:
  pscBaseUrl: http://localhost:3001
  pscSocketPath: ../cardano-devnet/devnet/ipc/node.socket
  pscKeptBlocks: 100
  pscNetworkId: "42" # Testnet network ID (main net = empty string)
  pscSlotConfig:
    scSlotZeroTime: 1663149193000
    scSlotLength: 1000 # In milliseconds
  pscInitialTxWallets:
    - getWallet: 1
    - getWallet: 2
  pscNodeMode: AlonzoNode
  pscProtocolParametersJsonPath: ../cardano-devnet/devnet/pparams.json

chainIndexConfig:
  ciBaseUrl: http://localhost:9083

requestProcessingConfig:
  requestProcessingInterval: 1

signingProcessConfig:
  spBaseUrl: http://localhost:9084
  spWallet:
    getWallet: 1

metadataServerConfig:
  mdBaseUrl: http://localhost:9085

developmentOptions:
  pabRollbackHistory: null
  pabResumeFrom:
    { "tag" : "PointAtGenesis" }
  monitoringConfig:
    monitoringPort: 9090
